services:
  devopsdb:
    image: dbimage
    ports: 
      - "3306:3306"
    deploy:
      replicas: 6
  appimage:
    image: appimage
    ports:
      - 8080:8080
    depends_on:
      - "devopsdb"
    deploy:
      replicas: 6